package com.clinic.healinghouse.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A one-off or recurring-generated clinic expense (requirements/Expenses_Requirements_v1.md §3.2)
 * — completely independent of the revenue catalog (Product/ClinicService/Tag). Soft-void lifecycle
 * only (§5.2): "delete" sets {@code status = VOIDED}, never removes the row.
 */
@Entity
@Table(name = "expense", indexes = {
        @Index(name = "idx_expense_date", columnList = "expenseDate"),
        @Index(name = "idx_expense_status", columnList = "status")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Expense {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "expense_category_id", nullable = false)
    private ExpenseCategory category;

    @Column(nullable = false)
    private LocalDate expenseDate;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    /** Free text for v1 — no managed Vendor entity (§2 non-goals). */
    private String vendorName;

    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    /** Set iff this expense is a salary/commission payout to a specific therapist (§5.4);
     *  null for every other category. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "therapist_id")
    private Therapist therapist;

    @Column(length = 1000)
    private String notes;

    // @JdbcTypeCode(VARCHAR) — see RolePermission.role javadoc for why: prevents this column from
    // becoming a native MySQL ENUM that can't widen if ExpenseStatus ever gains a third value.
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Builder.Default
    @Column(nullable = false)
    private ExpenseStatus status = ExpenseStatus.ACTIVE;

    /** Set iff this row was auto-generated by the recurring-expense scheduler (§5.3);
     *  null for a manually entered one-off expense. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recurring_expense_template_id")
    private RecurringExpenseTemplate sourceTemplate;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "recorded_by_user_id", nullable = false)
    private User recordedBy;

    @Version
    private Long version;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
